{% set name = "sentry-sdk" %}
{% set version = "1.9.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af0987fc074ada4a166bdc7e9d99d1da7811c6107e4b3416c7052ea1adb77dfc

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  host:
    # The package works on python 2, but the aiohttp integration
    # doesn't. Avoid syntax errors in install by building on 3.
    - python >=3
    - pip
  run:
    - python >=3
    - urllib3 >=1.10
    - certifi

test:
  requires:
    - pip
  imports:
    - sentry_sdk
  commands:
    - pip check

about:
  home: https://github.com/getsentry/sentry-python
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: The new Python SDK for Sentry.io
  description: |
    The new Python SDK for Sentry.io
  doc_url: https://docs.sentry.io/quickstart/?platform=python
  dev_url: https://github.com/getsentry/sentry-python

extra:
  recipe-maintainers:
    - alippai
    - dgasmith
    - djsutherland
